- stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/core.py
- stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/serializers.py
- stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/transactions.py
- stac_fastapi/elasticsearch/tests/clients/test_elasticsearch.py
> implement bulk transactions

- stac_fastapi/mongo/stac_fastapi/mongo/core.py
> add limited and count

- stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/transactions.py
- stac_fastapi/elasticsearch/tests/clients/test_elasticsearch.py
- #37 
Allow the items endpoint to accept a single item or a feature collection 
> Provide the option to insert a feature collection to the items endpoint

- stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/serializers.py
- stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/transactions.py
- #
Cleaning up and simplifying the transactions logic
> Clean up transactions logic

- stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/core.py
- #28
Bypass elasticsearch error messaging when indices aren't created which is confusing
> Create better error messaging when indices haven't been created yet

- stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/transactions.py
- n/a
replace use of RFC339 constant with equivalent code. That constant is both misnamed and no longer used in stac_pydantic, and may be removed in the future
> replace use of RFC339 constant with equivalent code

- stac_fastapi/elasticsearch/setup.py
- stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/datetime_utils.py
- stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/serializers.py
- stac_fastapi/elasticsearch/tests/resources/test_item.py
- n/a
Remove all uses of the deprecated datetime string DATETIME_RFC339.
> rework datetime values

- .pre-commit-config.yaml
- Dockerfile
- README.md
- stac_fastapi/elasticsearch/setup.py
- stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/core.py
- stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/serializers.py
- stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/transactions.py
> Reformat transactions, add docs, etc.

- .github/workflows/cicd.yml
- stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/app.py
- stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/core.py
- stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/indexes.py
- stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/transactions.py
- stac_fastapi/elasticsearch/tests/conftest.py
- https://github.com/stac-utils/stac-fastapi-elasticsearch/issues/43
1. Create indexes at startup instead of checking and creating if non-existent when ingesting
2. add a schema for the collections index
> create indexes at startup rather than when ingesting, add collection index schema

- docker-compose.yml
- stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/core.py
- stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/database_logic.py
- stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/indexes.py
- stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/transactions.py
- stac_fastapi/elasticsearch/tests/resources/test_item.py
- https://github.com/stac-utils/stac-fastapi-elasticsearch/issues/61
Pull db logic out of core and transaction.py to make codebase more modular.
> Pull database logic out of core.py and transaction.py

- stac_fastapi/elasticsearch/pytest.ini
- stac_fastapi/elasticsearch/setup.py
- stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/core.py
- stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/database_logic.py
- stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/indexes.py
- stac_fastapi/elasticsearch/tests/api/test_api.py
- stac_fastapi/elasticsearch/tests/clients/test_elasticsearch.py
- stac_fastapi/elasticsearch/tests/conftest.py
- stac_fastapi/elasticsearch/tests/resources/test_item.py
- https://github.com/stac-utils/stac-fastapi-elasticsearch/issues/70
- refactor tests to not need sleep
- use fixture for setup/teardown of most tests
- remove use of execute methods in ES DSL
> refactor tests to not need sleep, use fixture for setup/teardown

- Makefile
- stac_fastapi/elasticsearch/setup.py
- stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/app.py
- stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/config.py
- stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/core.py
- stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/database_logic.py
- stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/indexes.py
- stac_fastapi/elasticsearch/tests/api/test_api.py
- stac_fastapi/elasticsearch/tests/clients/test_elasticsearch.py
- stac_fastapi/elasticsearch/tests/conftest.py
- stac_fastapi/elasticsearch/tests/resources/test_collection.py
- stac_fastapi/elasticsearch/tests/resources/test_conformance.py
- stac_fastapi/elasticsearch/tests/resources/test_item.py
- stac_fastapi/elasticsearch/tests/resources/test_mgmt.py
- #60 
- https://github.com/stac-utils/stac-fastapi-elasticsearch/issues/51
- convert to use stac-fastapi Async base clients and AsyncElasticsearchClient
- refactor tests to use async
- refactor more tests to use the Context fixture
> convert to async and refactor tests

- stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/app.py
- n/a
IndexesClient().create_indexes() needs to be awaited. Missed this in the commits yesterday.
> await index creation

- .github/workflows/cicd.yml
- Makefile
- docker-compose.yml
- stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/config.py
- stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/indexes.py
- n/a
- configure the client with the ES_USER and ES_PASS vars passed in
- allow config of SSL
> add env vars to configure auth and ssl for ES instance

- docker-compose.yml
- stac_fastapi/elasticsearch/setup.py
- stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/core.py
- stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/database_logic.py
- stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/models/links.py
- stac_fastapi/elasticsearch/tests/api/test_api.py
- stac_fastapi/elasticsearch/tests/clients/test_elasticsearch.py
- stac_fastapi/elasticsearch/tests/conftest.py
- stac_fastapi/elasticsearch/tests/resources/test_item.py
- #26 
- #73 
- add next link with token-based pagination using ES search_after
- refactor to pass sort as a separate value rather than including in Search object
> add pagination with search_after, other refactoring

- stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/database_logic.py
- #80 
- run the sync bulk operation in an executor so it doesn't block the main thread.
> do bulk insert using asyncio executor instead of blocking

- stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/database_logic.py
- stac_fastapi/elasticsearch/tests/api/test_api.py
- stac_fastapi/elasticsearch/tests/resources/test_item.py
- https://github.com/stac-utils/stac-fastapi-elasticsearch/issues/76
Previously, the count and search ES requests were run sequentially, so every search request was delayed for as long as it took to get the complete count of matches.  This is an optional field in the Context Extension, and is generally not worth waiting on. 
Now, the code creates tasks for both the count and search, and only awaits the search task. If the count task isn't completed by the time the search is finished and its results serialized to Items, the count is ignored and the items. are returned.
Also note that we do not cancel the count task, so that it will complete and the ES cache will be populated with the results for the next similar query.
> run count and search concurrently, but don't wait for count to be done

- stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/app.py
- stac_fastapi/elasticsearch/tests/conftest.py
- https://github.com/stac-utils/stac-fastapi-elasticsearch/issues/89
- fields conformance class is advertised, but the behavior is not supported.
> remove fields extension advertisement, as this is not supported

- CHANGELOG.md
- stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/core.py
- stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/database_logic.py
- https://github.com/stac-utils/stac-fastapi-elasticsearch/issues/72
Moved db_to_stac serialization out of database_logic and into core.py for consistency
> Move db to stac serializer to core.py

- stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/database_logic.py
- n/a
The default behavior of the bulk api (which streams the individual operations in batches) is to immediately stop and raise an exception if any of the operations in a batch fail. Instead, don't raise on that error, and just keep ingesting the items. This is so that if there's a bad item that's being ingested, it doesn't prevent the others in the batch from being ingested. 
TBD is better reporting back to the caller as to which items succeeded and failed.
> for bulk operations, don't raise an exception if any of the ingested items fails

- README.md
- stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/core.py
- stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/extensions/filter.py
- n/a
- Improve queryables: add new one for nodata_pixel_percentage, reference the existing definitions correctly
- add documentation for copying elasticsearch indices
> improve queryables, add documentation for copying indicies

- .dockerignore
- Dockerfile.deploy
- n/a
- fix docker deploy image, which now requires gcc to build because of a new dependency
> fix docker deploy image

- .pre-commit-config.yaml
- stac_fastapi/elasticsearch/tests/resources/test_item.py
Flake8 is no longer hosted on GitLab. The pre-commit hook repo needed to be updated.
_(tests currently fail on my machine...out-of-scope to fix in this PR)_
> Follow flake8 to GitHub

- README.md
- N/A
While reading the README I noticed an errant backtick in a `pre-commit` command.
The change was made in the GitHub interface, and doesn't warrant changelog entries as the changes either fix a typo or add syntax highlighting.
> Fix a backtick typo; increase shell syntax usage

- .pre-commit-config.yaml
This upgrades the black and mypy hook versions.
Note that flake8 is upgraded separately in #123.
The mypy change introduced the following errors, which are now addressed by adding the `--explicit-package-bases` argument to the mypy invocation:
```
stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/datetime_utils.py: error: Source file found twice under different module names: "elasticsearch.datetime_utils" and "stac_fastapi.elasticsearch.datetime_utils"
stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/datetime_utils.py: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#mapping-file-paths-to-modules for more info
stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/datetime_utils.py: note: Common resolutions include: a) adding `__init__.py` …
```
> Update pre commit hooks

- CHANGELOG.md
- stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/database_logic.py
- #126
Allows to define custom ES index name for "collections" and "items"
> ES index names configurables

- .github/pull_request_template.md
- CHANGELOG.md
- Makefile
- README.md
- postman_collections/stac-fastapi-elasticsearch.postman_collection.json
- stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/app.py
- stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/config.py
- stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/core.py
- stac_fastapi/elasticsearch/tests/api/test_api.py
- stac_fastapi/elasticsearch/tests/conftest.py
- stac_fastapi/elasticsearch/tests/extensions/test_filter.py
- stac_fastapi/elasticsearch/tests/resources/test_item.py
- #30
Implements the Fields extension for GET and POST Search requests. [#127](https://github.com/stac-utils/stac-fastapi-elasticsearch/pull/127) should be reviewed first. 
> Implement fields extension

- CHANGELOG.md
- stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/extensions/filter.py
- stac_fastapi/elasticsearch/tests/extensions/test_filter.py
- #135
Searching items filtering by properties with floats returns wrong results. [Clause](https://github.com/stac-utils/stac-fastapi-elasticsearch/blob/main/stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/extensions/filter.py#L117) converts input query to ES filter using this Union. Because int is defined before float, all numeric values are converted to integer.
This fix takes care of value types, do not converting floats to int.
> [FIX-135]: Fix automatic converstion of float values to int

- .pre-commit-config.yaml
- CHANGELOG.md
- README.md
- examples/README.md
- examples/pip_docker/Dockerfile
- examples/pip_docker/docker-compose.yml
- examples/pip_docker/elasticsearch/config/elasticsearch.yml
- examples/pip_docker/scripts/wait-for-it-es.sh
- #
Added an example to run sfes from pip with docker and docker-compose files
> Pip docker example

- CHANGELOG.md
- stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/database_logic.py
- stac_fastapi/elasticsearch/tests/resources/test_item.py
- #153 
Remove unsupported characters from Elasticsearch index name, by converting uppercase characters to lowercase and removing a set of pre-defined characters.
https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-create-index.html#indices-create-api-path-params
> Remove unsupported characters from Elasticsearch index name

- CHANGELOG.md
- stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/database_logic.py
- #154 
Do not index `proj:geometry` and `proj:centroid` as geo fields.
> do not index proj:geometry and proj:centroid as geo fields

- CHANGELOG.md
- stac_fastapi/elasticsearch/setup.py
- stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/core.py
- stac_fastapi/elasticsearch/tests/extensions/test_filter.py
- #161 
Finish @philvarner previous work in implementing the filter extension for GET /search requests.
> GET filter extension requests

- .github/workflows/cicd.yml
- CHANGELOG.md
- README.md
- docker-compose.yml
- stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/core.py
- stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/database_logic.py
- stac_fastapi/elasticsearch/tests/api/test_api.py
- stac_fastapi/elasticsearch/tests/clients/test_elasticsearch.py
- stac_fastapi/elasticsearch/tests/conftest.py
- stac_fastapi/elasticsearch/tests/extensions/test_filter.py
- stac_fastapi/elasticsearch/tests/resources/test_collection.py
- stac_fastapi/elasticsearch/tests/resources/test_conformance.py
- stac_fastapi/elasticsearch/tests/resources/test_item.py
- stac_fastapi/elasticsearch/tests/resources/test_mgmt.py
> Collection pagination

- CHANGELOG.md
- stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/core.py
- stac_fastapi/elasticsearch/tests/api/test_api.py
- #166 
Exclude unset fields in search response when Fields extension is enabled.
> Exclude unset fields in search response

- CHANGELOG.md
- stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/core.py
- stac_fastapi/elasticsearch/tests/extensions/test_filter.py
- #179 
Set correct default filter-lang for GET /search requests
> Set correct default filter-lang for GET /search requests

- stac_fastapi/opensearch/stac_fastapi/opensearch/config.py
- #199 
Changes the OpenSearch config `ssl_version` to the default `ssl.PROTOCOL_SSLv23`. All other options throw an unsupported protocol error. Source: https://opensearch-project.github.io/opensearch-py/_modules/opensearchpy/connection/http_urllib3.html
- [ x ] Changes are added to the changelog
> OpenSearch ssl_version

- CHANGELOG.md
- stac_fastapi/core/stac_fastapi/core/core.py
- stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/database_logic.py
- stac_fastapi/opensearch/stac_fastapi/opensearch/database_logic.py
- #195 
Removing the es-specific language from core.py makes it easier to use other databases with the api core package in the future. 
> remove db logic from all collections in core.py

- CHANGELOG.md
- docker-compose.yml
- stac_fastapi/elasticsearch/README.md
- stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/app.py
- stac_fastapi/opensearch/README.md
- stac_fastapi/opensearch/stac_fastapi/opensearch/app.py
- #206 
Adds API `title` and `description` parameters from environment variables `STAC_API_TITLE` and `STAC_API_DESCRIPTION`, respectively.
> Enable custom API title and description

- CHANGELOG.md
- stac_fastapi/core/stac_fastapi/core/core.py
- stac_fastapi/core/stac_fastapi/core/serializers.py
- stac_fastapi/tests/resources/test_collection.py
- #210 
Do not overwrite links when serializing Item and Collection objects before persisting them in the database. Implemented the `CollectionSerializer.stac_to_db()` method to handle this operation.
Also do not store inferred links in the database, they will be added when loading objects from the database with the `Serializer.db_to_stac()` method.
> Don't overwrite links before persisting Item/Collection in database

- CHANGELOG.md
- README.md
- stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/app.py
- stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/database_logic.py
- stac_fastapi/opensearch/stac_fastapi/opensearch/app.py
- stac_fastapi/opensearch/stac_fastapi/opensearch/database_logic.py
- stac_fastapi/tests/conftest.py
- stac_fastapi/tests/database/test_database.py
- #208 
Use index templates for Collection and Item indices.
> Index templates

- stac_fastapi/opensearch/stac_fastapi/opensearch/database_logic.py
Fixing a bug in the OpenSearch `database_logic.py` `get_all_collections` where the index was hardcoded to "collections"
> get_all_collections index fix

- CHANGELOG.md
- stac_fastapi/core/stac_fastapi/core/models/links.py
- stac_fastapi/tests/resources/test_item.py
- closes #213 
URL encode the `next` href
> URL encode next href

- CHANGELOG.md
- examples/README.md
- examples/pip_docker/Dockerfile
- examples/pip_docker/docker-compose.yml
- #
Updated the pip_docker example to use stac-fastapi.elasticsearch 2.1.0 and the elasticsearch 8.11.0 docker image.
> Update pip-docker example

- CHANGELOG.md
- README.md
- stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/app.py
- stac_fastapi/opensearch/stac_fastapi/opensearch/app.py
- #220 
This enables a user to define an API root path. This provides a workaround for the issue described [here](https://github.com/stac-utils/stac-fastapi-elasticsearch-opensearch/issues/220). The PR also includes a readme section about configuring the API environment variables.
> Add API root path environment variable

- CHANGELOG.md
- stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/config.py
- stac_fastapi/opensearch/stac_fastapi/opensearch/config.py
- #214 
Changes the default `ca_certs`  value to use `certifi.where()` to find the installed certificate authority. Makes it more flexible I think.
> Default to use cerifi.where() to find the ca_certs 

- README.md
> Update README.md - spelling mistake

- CHANGELOG.md
- stac_fastapi/core/stac_fastapi/core/core.py
- https://github.com/stac-utils/stac-fastapi-elasticsearch-opensearch/issues/235
Fixed `POST /collections/test-collection/items` returning an item with an empty `links` array.
> core create_item fix

- CHANGELOG.md
- stac_fastapi/core/stac_fastapi/core/core.py
- stac_fastapi/tests/resources/test_item.py
- https://github.com/Healy-Hyperspatial/stac-fastapi-mongo/issues/20
Always generate links for all searches, since now base links are generated on the request and no longer stored.
> Always generate links for all searches

- CHANGELOG.md
- stac_fastapi/tests/resources/test_item.py
- #242 
Added a test to ensure that pagination correctly returns expected links, particularly verifying the absence of a 'next' link on the last page of results.
> Add pagination test to verify the absence of a 'next' link on the last page of results

- CHANGELOG.md
- stac_fastapi/core/stac_fastapi/core/core.py
- stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/database_logic.py
- stac_fastapi/opensearch/stac_fastapi/opensearch/database_logic.py
- stac_fastapi/tests/resources/test_item.py
- https://github.com/stac-utils/stac-fastapi-elasticsearch-opensearch/issues/242
**Merge dependencie(s):**
- https://github.com/stac-utils/stac-fastapi-elasticsearch-opensearch/pull/241
- Paginated search queries now don't return a token on the last page.
- Made some fixes to the respective tests. In particular `test_pagination_token_idempotent` had and indentation issue
- Improved `execute_search` to make use of  `es_response["hits"]["total"]["value"]`
> Paginated search queries now don't return a token on the last page

- CHANGELOG.md
- README.md
- stac_fastapi/core/README.md
- stac_fastapi/elasticsearch/README.md
- stac_fastapi/opensearch/README.md
- None
Add symlinks from project-specific readme files to main readme. This will improve the pypi release page. https://pypi.org/project/stac-fastapi.elasticsearch/
> Add symlinks to publish readme to pypi

- CHANGELOG.md
- stac_fastapi/core/stac_fastapi/core/core.py
- stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/app.py
- stac_fastapi/opensearch/stac_fastapi/opensearch/app.py
- stac_fastapi/tests/api/test_api.py
- stac_fastapi/tests/conftest.py
- stac_fastapi/tests/resources/test_item.py
- https://github.com/radiantearth/stac-api-spec/issues/396
- https://github.com/stac-utils/pgstac/pull/254
> Remove deprecated context extension

- CHANGELOG.md
- stac_fastapi/tests/api/test_api.py
- #262 
Edit to four tests of the sort extension. The timezone `Z` character was not being included with the `.replace` command. So it was removed and `Z` is appended to the datetime string.
> Repair API sort tests

- CHANGELOG.md
- stac_fastapi/core/stac_fastapi/core/extensions/aggregation.py
- stac_fastapi/tests/extensions/test_aggregation.py
- Two bug fixes for the aggregation logic
> Aggregation bugfix

- stac_fastapi/tests/clients/test_elasticsearch.py
- stac_fastapi/tests/resources/test_item.py
The test suite is throwing many `DeprecationWarning`s and `UserWarning`s.
This PR addresses only one class: a pydantic 2.0 `DeprecationWarning` caused by `.dict()` calls in the test suite itself.
> Fix some pydantic 2.0 `DeprecationWarning`s

- .github/workflows/cicd.yml
Currently, all CI jobs emit warnings due to `actions/cache@v3`, which uses an old Node.js version ([recent example](https://github.com/stac-utils/stac-fastapi-elasticsearch-opensearch/actions/runs/10507540026)).
> ![image](https://github.com/user-attachments/assets/bd0ea622-1ff4-4d16-8762-69307a79d5f8)
However, on inspection, it appears that `actions/cache` is configured incorrectly:
* There are no lock files for it to hash, resulting in a blank portion in the cache key ([caches generated in CI](https://github.com/stac-utils/stac-fastapi-elasticsearch-opensearch/actions/caches)).
> ![image](https://github.com/user-attachments/assets/9b980b18-d9df-49ae-9bc4-21223216b0bb)
* The comments in the YAML claim that it's caching for pipenv, but then caches the pip directory …
> Remove `actions/cache` in favor of `actions/setup-python` caching

- CHANGELOG.md
- stac_fastapi/core/stac_fastapi/core/extensions/filter.py
- stac_fastapi/tests/extensions/test_cql2_like_to_es.py
- Closes #285
This is a break/fix PR. The first commit adds a suite of tests that document correct LIKE-to-wildcard query value conversions, and then fixes the `cql2_like_to_es()` code to correctly process escaped backslashes.
_(`make test` fails because the Docker container port ranges don't match, but CI, which doesn't use `make test`, passes)_
_n/a, no docs in repo_
> Make `cql2_like_to_es()` understand escaped backslashes

- CHANGELOG.md
- stac_fastapi/core/stac_fastapi/core/version.py
- stac_fastapi/elasticsearch/setup.py
- stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/version.py
- stac_fastapi/opensearch/setup.py
- stac_fastapi/opensearch/stac_fastapi/opensearch/version.py
> Update to v3.1.0

- CHANGELOG.md
- stac_fastapi/core/stac_fastapi/core/extensions/aggregation.py
- stac_fastapi/tests/extensions/test_aggregation.py
N/A
Fixes the `self` link in the response of the `/collections/{collection_id}/aggregations` request. The collection ID segment was missing in the URL because of the relative path URL construction.
> Aggregation self link with collection specified

- CHANGELOG.md
- stac_fastapi/core/stac_fastapi/core/extensions/aggregation.py
- stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/database_logic.py
- stac_fastapi/opensearch/stac_fastapi/opensearch/database_logic.py
N/A
Refactor `aggregate()` in database logic to allow extending the supported set of aggregations. The mapping of aggregation name to Elasticsearch/OpenSearch functionality was in the `aggregate()` function, which made it difficult to alter the set of supported aggregations. I moved the mapping to a property of the database logic, so it can be modified when the database logic is instantiated. 
> refactor aggregate in database_logic

- CHANGELOG.md
- README.md
- docker-compose.yml
- examples/rate_limit/docker-compose.rate_limit.yml
- stac_fastapi/core/setup.py
- stac_fastapi/core/stac_fastapi/core/rate_limit.py
- stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/app.py
- stac_fastapi/opensearch/stac_fastapi/opensearch/app.py
- stac_fastapi/tests/basic_auth/test_basic_auth.py
- stac_fastapi/tests/conftest.py
- stac_fastapi/tests/rate_limit/test_rate_limit.py
Implementation of address based global rate limiting **option**.
Rate limiting is an optional security feature that controls API request frequency on a remote address basis. It's enabled by setting the `STAC_FASTAPI_RATE_LIMIT` environment variable, e.g., `500/minute`. This limits each client to 500 requests per minute, helping prevent abuse and maintain API stability. Implementation examples are available in the [examples/rate_limit](examples/rate_limit) directory.
> Rate limit implementation

- .github/workflows/publish.yml
- CHANGELOG.md
- stac_fastapi/core/stac_fastapi/core/version.py
- stac_fastapi/elasticsearch/setup.py
- stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/version.py
- stac_fastapi/opensearch/setup.py
- stac_fastapi/opensearch/stac_fastapi/opensearch/version.py
- add publish.yml to automatically push new releases to PyPI
- update sfeos to v3.2.0
> Publish to PyPI in gh actions

- CHANGELOG.md
- stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/database_logic.py
- stac_fastapi/opensearch/stac_fastapi/opensearch/database_logic.py
- #322 
Use base64 encoded JSON string of sort keys as pagination token instead of comma separated string.
> fix: use base64 encoded JSON string of sort keys as pagination token

- CHANGELOG.md
- stac_fastapi/core/stac_fastapi/core/version.py
- stac_fastapi/elasticsearch/setup.py
- stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/version.py
- stac_fastapi/opensearch/setup.py
- stac_fastapi/opensearch/stac_fastapi/opensearch/version.py
> Release v3.2.2

- CHANGELOG.md
- examples/auth/README.md
- #310
Using multiple authentication dependencies on a single route can cause clashes if not done correctly (merging them). This is particularly relevant to the default `*` route. My [pull request](https://github.com/stac-utils/stac-fastapi/pull/766) on [stac-fastapi](https://github.com/stac-utils/stac-fastapi) to dynamically merge multiple dependencies was rejected and I don't think it's possible to replicate it here. So I've added a note to the dependency documentation to try to explain what to do in this case.
> Adding note on the use of the default `*` use in route authentication dependecies

- CHANGELOG.md
- README.md
- stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/database_logic.py
- stac_fastapi/opensearch/stac_fastapi/opensearch/database_logic.py
- stac_fastapi/tests/database/test_database.py
- #328 
Separating alias and index names to allow for aliases to include capitalisation. Index names now include the lowered and hex encoded collection ID to prevent clashes of indices. 
> Allow capitals in item index aliases

- .github/workflows/cicd.yml
- CHANGELOG.md
- stac_fastapi/core/setup.py
- stac_fastapi/elasticsearch/setup.py
- stac_fastapi/opensearch/setup.py
It's not an issue. We simply want to support python 3.13 in stac_fastapi.core via removing **type_extension**!
- #
It;s gonna close issue #335 as well
> Support Py3.13

- CHANGELOG.md
- stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/config.py
- stac_fastapi/opensearch/stac_fastapi/opensearch/config.py
- #348 
Allow to configure multiple Elasticsearch/OpenSearch hosts (comma-separated) and enable `http_compress` by default.
> feat: more configuration options for Elasticsearch/OpenSearch

- CHANGELOG.md
- stac_fastapi/core/setup.py
- stac_fastapi/core/stac_fastapi/core/core.py
- stac_fastapi/core/stac_fastapi/core/database_logic.py
- stac_fastapi/core/stac_fastapi/core/extensions/query.py
- stac_fastapi/core/stac_fastapi/core/models/links.py
- stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/app.py
- stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/database_logic.py
- stac_fastapi/opensearch/stac_fastapi/opensearch/app.py
- stac_fastapi/opensearch/stac_fastapi/opensearch/database_logic.py
- stac_fastapi/tests/rate_limit/test_rate_limit.py
- Fixes https://github.com/stac-utils/stac-fastapi-elasticsearch-opensearch/issues/345
- Fixes https://github.com/stac-utils/stac-fastapi-elasticsearch-opensearch/issues/344
- Fixes https://github.com/stac-utils/stac-fastapi-elasticsearch-opensearch/issues/336
This PR consists of self-contained commits (except the first commit that provides database_logic deduplication), making it easy to change or remove individual patches. It addresses several small issues, improves the performance of certain methods, and adds support for dynamically-generated queryables. This enhancement doesn't require any new configuration as queryables are generated on the fly based on the os/es mappings. The implementation is designed for extensibility, with built-in logic for …
> Zero-config dynamically-generated queryables, Performance fixes

- CHANGELOG.md
- stac_fastapi/core/stac_fastapi/core/core.py
- #75 
- Changed item update operation to use Elasticsearch index API instead of delete and create for better efficiency and atomicity.
> Update item method fix

- CHANGELOG.md
- README.md
- stac_fastapi/core/stac_fastapi/core/core.py
- stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/config.py
- stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/database_logic.py
- stac_fastapi/opensearch/stac_fastapi/opensearch/config.py
- stac_fastapi/opensearch/stac_fastapi/opensearch/database_logic.py
- stac_fastapi/tests/api/test_api.py
- stac_fastapi/tests/clients/test_es_os.py
- #346 
- Added logging to bulk insertion methods to provide detailed feedback on errors encountered during operations. 
- Introduced the `RAISE_ON_BULK_ERROR` environment variable to control whether bulk insertion methods raise exceptions on errors (`true`) or log warnings and continue processing (`false`). 
> Enable choice of raising bulk insert errors, logging

- CHANGELOG.md
- data_loader.py
- stac_fastapi/elasticsearch/setup.py
- stac_fastapi/opensearch/setup.py
- **requests** was only required for data_loader, replaced it with **httpx**
- there were a few inefficiencies in handling large numbers of files
- **json** package was replaced with **orjson** as it's part of the core
- `except requests.ConnectionError` blocks were removed as they obfuscated real error messages and *muted* app failure exit codes, making it difficult to integrate
- added is_file checks to avoid consuming directories with weird names
> Drop `requests` dependency and optimize data_loader

- CHANGELOG.md
- Makefile
- stac_fastapi/core/stac_fastapi/core/base_database_logic.py
- stac_fastapi/core/stac_fastapi/core/extensions/filter.py
- stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/app.py
- stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/database_logic.py
- stac_fastapi/opensearch/stac_fastapi/opensearch/app.py
- stac_fastapi/opensearch/stac_fastapi/opensearch/database_logic.py
- stac_fastapi/sfeos_helpers/stac_fastapi/sfeos_helpers/filter/client.py
- stac_fastapi/tests/conftest.py
- stac_fastapi/tests/extensions/test_filter.py
This enables support for generating "enum" fields for selected queryables. There is also now a concept of optional queryable parameters - so it's possible to indicate enum fields without requiring that field to be present in all collections. This enum generation is very efficient as it's basically an index-only scan.
```
"platform": {
"description": "Satellite platform identifier",
"title": "Platform",
"type": "string",
"enum": [
"sentinel-2a"
]
},
```
Other small changes include adding the previously missing get_items_mapping abstract to the base database logic. I also got confused by the existence of "OS_HOST" and "OS_PORT" variables in the Makefile which appear to be unused, so I simply removed them too.
> Add support for optional enum queryables

- CHANGELOG.md
- compose.yml
- examples/auth/compose.basic_auth.yml
- examples/auth/compose.oauth2.yml
- examples/auth/compose.route_dependencies.yml
- examples/rate_limit/compose.rate_limit.yml
- stac_fastapi/core/stac_fastapi/core/version.py
- stac_fastapi/elasticsearch/setup.py
- stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/app.py
- stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/version.py
- stac_fastapi/opensearch/setup.py
- stac_fastapi/opensearch/stac_fastapi/opensearch/app.py
- stac_fastapi/opensearch/stac_fastapi/opensearch/version.py
- stac_fastapi/sfeos_helpers/setup.py
- stac_fastapi/sfeos_helpers/stac_fastapi/sfeos_helpers/version.py
- Added support for PATCH update through  [RFC 6902](https://datatracker.ietf.org/doc/html/rfc6902) and [RFC 7396](https://datatracker.ietf.org/doc/html/rfc7396) [#291](https://github.com/stac-utils/stac-fastapi-elasticsearch-opensearch/pull/291)
- Updated stac-fastapi parent libraries to v6.0.0 [#291](https://github.com/stac-utils/stac-fastapi-elasticsearch-opensearch/pull/291)
> Update to v6.0.0

- CHANGELOG.md
- stac_fastapi/core/stac_fastapi/core/datetime_utils.py
Fixes an issue in the OS STAC `/search` endpoint where datetime filters overwrite milliseconds. The queries return products outside the specified range because the filter was rounding datetimes to full seconds. This change ensures that milliseconds are preserved, so datetime filtering returns correct results.
> Ensure Normalize func preserves milliseconds precision

- CHANGELOG.md
- README.md
- stac_fastapi/core/stac_fastapi/core/utilities.py
- stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/database_logic.py
- stac_fastapi/opensearch/stac_fastapi/opensearch/database_logic.py
- stac_fastapi/tests/api/test_api.py
This PR adds a environment variable `ENV_MAX_LIMIT`, which allows overriding the default `MAX_LIMIT` value, which   controls the `?limit` URL parameter used in STAC API queries, defining the maximum number of items and collections that can be returned in a single response. 
> feat: Add env var ENV_MAX_LIMIT for items returned

- CHANGELOG.md
- stac_fastapi/core/stac_fastapi/core/core.py
The `/collections/{collection_id}/bulk_items` endpoint does not work when `ENABLE_DATETIME_INDEX_FILTERING` is set to true, as only the async `/collections/{collection_id}/items` version was implemented while the sync `/collections/{collection_id}/bulk_items` wasn't. This PR blocks the /bulk_items endpoint when `ENABLE_DATETIME_INDEX_FILTERING` is set to true.
> Blocking bulk_items endpoint when ENABLE_DATETIME_INDEX_FILTERING

- .pre-commit-config.yaml
- CHANGELOG.md
- compose.yml
- examples/auth/compose.basic_auth.yml
- examples/auth/compose.oauth2.yml
- examples/auth/compose.route_dependencies.yml
- examples/rate_limit/compose.rate_limit.yml
- stac_fastapi/core/stac_fastapi/core/version.py
- stac_fastapi/elasticsearch/setup.py
- stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/app.py
- stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/version.py
- stac_fastapi/opensearch/setup.py
- stac_fastapi/opensearch/stac_fastapi/opensearch/app.py
- stac_fastapi/opensearch/stac_fastapi/opensearch/version.py
- stac_fastapi/sfeos_helpers/setup.py
- stac_fastapi/sfeos_helpers/stac_fastapi/sfeos_helpers/database/utils.py
- stac_fastapi/sfeos_helpers/stac_fastapi/sfeos_helpers/version.py
> Release v6.3.0

- CHANGELOG.md
- README.md
- stac_fastapi/core/stac_fastapi/core/core.py
- stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/app.py
- stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/database_logic.py
- stac_fastapi/opensearch/stac_fastapi/opensearch/app.py
- stac_fastapi/opensearch/stac_fastapi/opensearch/database_logic.py
- stac_fastapi/tests/api/test_api_search_collections.py
- #459 
- Added support for both cql2-json and cql2-text in GET /collections 
> GET /collections filter extension

- .gitignore
- CHANGELOG.md
- stac_fastapi/sfeos_helpers/stac_fastapi/sfeos_helpers/filter/client.py
during testing I realized that sfoes skips check on nested attributes in the mapping. In result everything from properties is passed to ...collection/.../queryables endpoint.
Example mapping:
```
{
"mappings": {
"dynamic_templates": [
{
"descriptions": {
"match": "description",
"match_mapping_type": "string",
"mapping": {
"type": "text"
}
}
},
{
"titles": {
"match": "title",
"match_mapping_type": "string",
"mapping": {
"type": "text"
}
}
},
{
"proj_epsg": {
"match": "proj:epsg",
"mapping": {
"type": "integer"
}
}
},
{
"proj_projjson": {
"match": "proj:projjson",
"mapping": {
"enabled": false,
"type": "object"
}
}
},
{
"proj_centroid": {
"match": "proj:centroid",
"mapping": {
"type": "geo_point"
}
}
},
{
"proj_geometry": {
"match": "proj:geometry",
"mapping": {
"enabled": …
```
> Support for disabling attributes nested in properties.
