stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/config.py
stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/transactions.py

change mappings

---

stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/transactions.py
stac_fastapi/elasticsearch/tests/data/test_item.json

add check for floats

---

.github/workflows/publish-to-test-pypi.yml

update build command

---

.github/workflows/publish-to-pypi.yml
stac_fastapi/elasticsearch/setup.py
stac_fastapi/mongo/setup.py

clean up publishing

---

.github/workflows/publish-to-test-pypi.yml
stac_fastapi/elasticsearch/setup.py
stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/version.py
stac_fastapi/mongo/setup.py

mongo 2.3.0

---

postman_collections/stac-fastapi-elasticsearch.postman_collection.json

This will make it much easier for people to contribute I think

add postman collection to repo

---

CHANGELOG.md
stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/core.py
stac_fastapi/elasticsearch/tests/api/test_api.py

- #93 
Fix intersection search in core.py 

Fix search request intersection

---

.gitignore
docker-compose.yml
elasticsearch/config/elasticsearch.yml

- n/a
Add config to allow snapshot and restore from local filesystem.
Will add documentation later on how to actually do these operations, after I've done it more.

add local config to allow for snapshot/restore from local filesystem

---

stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/core.py
stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/database_logic.py
stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/serializers.py

General update - add docstrings

---

CHANGELOG.md
stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/core.py
stac_fastapi/elasticsearch/tests/api/test_api.py

Enable GET /search intersection

---

stac_fastapi/elasticsearch/tests/conftest.py
stac_fastapi/elasticsearch/tests/resources/test_mgmt.py

Fix event loop

---

stac_fastapi/elasticsearch/setup.py
stac_fastapi/opensearch/setup.py

core dependency to v2.0.0

---

stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/database_logic.py
stac_fastapi/opensearch/stac_fastapi/opensearch/database_logic.py

- #197 
Adds an explicit mapping for collection id field. 
- [ x ] Changes are added to the changelog

Collection id keyword mapping

---

CHANGELOG.md

Missed the changelog after marking it complete. Update to keep in sync.
- [ x ] Changes are added to the changelog

Changelog update for #200

---

CHANGELOG.md
stac_fastapi/core/stac_fastapi/core/version.py
stac_fastapi/elasticsearch/setup.py
stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/version.py
stac_fastapi/opensearch/setup.py
stac_fastapi/opensearch/stac_fastapi/opensearch/version.py

update to v2.3.0

---

CHANGELOG.md
stac_fastapi/core/stac_fastapi/core/version.py
stac_fastapi/elasticsearch/setup.py
stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/version.py
stac_fastapi/opensearch/setup.py
stac_fastapi/opensearch/stac_fastapi/opensearch/version.py

update to v2.3.1

---

CHANGELOG.md
stac_fastapi/tests/resources/test_item.py

Unskip temporal open window test

---

CHANGELOG.md
docker-compose.basic_auth_protected.yml
docker-compose.basic_auth_public.yml
docker-compose.yml
stac_fastapi/core/stac_fastapi/core/version.py
stac_fastapi/elasticsearch/setup.py
stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/version.py
stac_fastapi/opensearch/setup.py
stac_fastapi/opensearch/stac_fastapi/opensearch/version.py

Update to v3.0.0a1

---

CHANGELOG.md
docker-compose.basic_auth_protected.yml
docker-compose.basic_auth_public.yml
docker-compose.yml
stac_fastapi/core/stac_fastapi/core/version.py
stac_fastapi/elasticsearch/setup.py
stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/version.py
stac_fastapi/opensearch/setup.py
stac_fastapi/opensearch/stac_fastapi/opensearch/version.py

Release sfeos v3.0.0a2

---

CHANGELOG.md
stac_fastapi/core/stac_fastapi/core/models/links.py

- #296
Updating `CollectionLinks` to generate correct `self` link for `collections` endpoint.

Updating collection self link for collections page.

---

CHANGELOG.md
stac_fastapi/core/stac_fastapi/core/version.py
stac_fastapi/elasticsearch/setup.py
stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/version.py
stac_fastapi/opensearch/setup.py
stac_fastapi/opensearch/stac_fastapi/opensearch/version.py

update for v3.2.3

---

CHANGELOG.md
stac_fastapi/core/stac_fastapi/core/version.py
stac_fastapi/elasticsearch/setup.py
stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/version.py
stac_fastapi/opensearch/setup.py
stac_fastapi/opensearch/stac_fastapi/opensearch/version.py

Update version to v3.2.4

---

CHANGELOG.md
compose.yml
examples/auth/compose.basic_auth.yml
examples/auth/compose.oauth2.yml
examples/auth/compose.route_dependencies.yml
examples/rate_limit/compose.rate_limit.yml
stac_fastapi/core/stac_fastapi/core/version.py
stac_fastapi/elasticsearch/setup.py
stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/app.py
stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/version.py
stac_fastapi/opensearch/setup.py
stac_fastapi/opensearch/stac_fastapi/opensearch/app.py
stac_fastapi/opensearch/stac_fastapi/opensearch/version.py
stac_fastapi/sfeos_helpers/setup.py
stac_fastapi/sfeos_helpers/stac_fastapi/sfeos_helpers/version.py

Publish release 6.1.0

---

CHANGELOG.md
README.md
stac_fastapi/core/stac_fastapi/core/core.py
stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/database_logic.py
stac_fastapi/opensearch/stac_fastapi/opensearch/database_logic.py
stac_fastapi/sfeos_helpers/stac_fastapi/sfeos_helpers/mappings.py
stac_fastapi/tests/api/test_api_search_collections.py

GET /collections search datetime
